### ISSUE TITLE
**_Sakib_**, is there any branch created on your side or you created the branch "new-feature" ? @Sakibdevlekar

### ISSUE THREAD

**Issue by nil2022** [nil2022/CRM_App#37]
**_Sakib_**, is there any branch created on your side or you created the branch "new-feature" ? @Sakibdevlekar 
![Screenshot 2024-01-03 191543](https://github.com/nil2022/CRM_App/assets/105872070/828d37c1-d4a3-4d5c-be17-d385c20f576f)

_Originally posted by @nil2022 in https://github.com/nil2022/CRM_App/discussions/19#discussioncomment-8003044_

**Comment by Sakibdevlekar** [comment]
new-feature branch deleted issue closed
